title: Idea Protocol
description: Standard, plain-language licenses for sharing and discussing ideas without NDAs or awkwardness.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Github: https://github.com/lalithaar/idea-protocol
